let subjects = [
  {
    id: 1,
    name: "Bicycle",
    items: [
      "Il fait tu - 30?",
      "Pis ma grand-mère et son frigo à déménager",
      "Lycra cuissards et foufounnes",
      "Ils font pas leurs stops",
      "Des tickets pour les bécyks",
      "Vas donc rouler sul trottoire",
      "Les pistes déneigées avant le reste!",
      "C'est l'hiver 14 mois par année",
      "La piste va générer de la pollution",
      "Armoire normande",
      "Immatriculation!",
      "Les places de stationnement!",
      "NIMBY",
      "Du temps de qualité dans mon péquope en famille",
      "Conducteur persécuté",
      "Les bécyks c'est pour les kids",
      "Anecdote personnelle",
      "Les commerces vont fermer",
      "Ils payent pas pour les routes!",
      "Ils sont courageux (gracieuseté MTQ)",
      "La piste va induire du traffic",
      "Tout ça pour 2-3 cyclistes, toujours les mêmes",
      "Moé je paye des taxes pis pas eux",
      "Yavait tu son casse?",
      "Cite une loi non existante",
    ],
  },
  {
    id: 2,
    name: "Tramway",
    items: [
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "NIMBY",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
  },
  {
    id: 3,
    name: "Ville 15 minutes",
    items: [
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "NIMBY",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
  },
  {
    id: 2,
    name: "Drag Queens",
    items: [
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "NIMBY",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
  },
  {
    id: 3,
    name: "3e lien (Annulé)",
    items: [
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "NIMBY",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
      "",
    ],
  },
];

export function getSubjects() {
  return subjects.map((subject) => subject.name);
}

export function getSubjectItems(name) {
  const subject = subjects.find((subject) => subject.name === name);
  return subject ? subject.items?.filter((item) => item !== null) : [""];
}

//  To use when fetch from an api.
// const getData = async <T>(url: string): Promise<T> => {
//   const response = await fetch(url);
//   return await response.json();
// }
